# Generated constants from Python codebase
# Do not edit this file directly. Edit src/constants.py instead.

# Target organization
TARGET_ORG="mcp-research"

# Property name for last scan timestamp
GHAS_STATUS_UPDATED="GHAS_Status_Updated"

# Property names for total alert counts
CODE_ALERTS="CodeAlerts"
SECRET_ALERTS="SecretAlerts"
DEPENDENCY_ALERTS="DependencyAlerts"

# Property names for code scanning alerts by severity
CODE_ALERTS_CRITICAL="CodeAlerts_Critical"
CODE_ALERTS_HIGH="CodeAlerts_High"
CODE_ALERTS_MEDIUM="CodeAlerts_Medium"
CODE_ALERTS_LOW="CodeAlerts_Low"

# Property names for secret scanning alerts
SECRET_ALERTS_TOTAL="SecretAlerts_Total"
SECRET_ALERTS_BY_TYPE="SecretAlerts_By_Type"

# Property names for dependency alerts by severity
DEPENDENCY_ALERTS_CRITICAL="DependencyAlerts_Critical"
DEPENDENCY_ALERTS_HIGH="DependencyAlerts_High"
DEPENDENCY_ALERTS_MODERATE="DependencyAlerts_Moderate"
DEPENDENCY_ALERTS_LOW="DependencyAlerts_Low"