#!/usr/bin/env python3
"""
This script exports the constants from the Python codebase to a format consumable by shell scripts.
Run this script to generate a constants.sh file that can be sourced by shell scripts.
"""

from src.constants import *

def generate_shell_constants():
    """Generate a shell script with constants from the Python codebase."""
    constants = [
        f"# Generated constants from Python codebase",
        f"# Do not edit this file directly. Edit src/constants.py instead.",
        f"",
        f"# Target organization",
        f"TARGET_ORG=\"{TARGET_ORG}\"",
        f"",
        f"# Property name for last scan timestamp",
        f"GHAS_STATUS_UPDATED=\"{GHAS_STATUS_UPDATED}\"",
        f"",
        f"# Property names for total alert counts",
        f"CODE_ALERTS=\"{CODE_ALERTS}\"",
        f"SECRET_ALERTS=\"{SECRET_ALERTS}\"",
        f"DEPENDENCY_ALERTS=\"{DEPENDENCY_ALERTS}\"",
        f"",
        f"# Property names for code scanning alerts by severity",
        f"CODE_ALERTS_CRITICAL=\"{CODE_ALERTS_CRITICAL}\"",
        f"CODE_ALERTS_HIGH=\"{CODE_ALERTS_HIGH}\"",
        f"CODE_ALERTS_MEDIUM=\"{CODE_ALERTS_MEDIUM}\"",
        f"CODE_ALERTS_LOW=\"{CODE_ALERTS_LOW}\"",
        f"",
        f"# Property names for secret scanning alerts",
        f"SECRET_ALERTS_TOTAL=\"{SECRET_ALERTS_TOTAL}\"",
        f"SECRET_ALERTS_BY_TYPE=\"{SECRET_ALERTS_BY_TYPE}\"",
        f"",
        f"# Property names for dependency alerts by severity",
        f"DEPENDENCY_ALERTS_CRITICAL=\"{DEPENDENCY_ALERTS_CRITICAL}\"",
        f"DEPENDENCY_ALERTS_HIGH=\"{DEPENDENCY_ALERTS_HIGH}\"",
        f"DEPENDENCY_ALERTS_MODERATE=\"{DEPENDENCY_ALERTS_MODERATE}\"",
        f"DEPENDENCY_ALERTS_LOW=\"{DEPENDENCY_ALERTS_LOW}\"",
    ]
    
    return "\n".join(constants)

if __name__ == "__main__":
    shell_constants = generate_shell_constants()
    with open("constants.sh", "w") as f:
        f.write(shell_constants)
    print("Generated constants.sh file for shell scripts.")