name: "Actionlint Workflow Check"

on:
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '30 5 * * 1'  # Run at 05:30 UTC every Monday

permissions:
  contents: read
  pull-requests: write

jobs:
  actionlint:
    name: Lint GitHub Actions Workflows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Run Actionlint
        uses: devops-actions/actionlint@469810fd82c015d3c43815cd2b0e4d02eecc4819 # v0.1.11
        id: actionlint